site_name: Wiki
site_url: https://wiki.vinrobot.net
repo_url: https://github.com/Vinrobot/wiki.vinrobot.net

theme:
  name: readthedocs
  prev_next_buttons_location: none

markdown_extensions:
  attr_list:
  pymdownx.magiclink:
